### ISSUE TITLE
Function hangs Android App on Simulator (Bluestacks)

### ISSUE THREAD

**Issue by jkorn2324** [fxnai/fxn3d#11] opened 2024-11-11 23:38 UTC
**Issue:** A crash on Function causes the unity app to never finish loading & to remain stuck on the Unity loading screen.

**Expected Output:** It should open the game.

**Unity + Function Specs:**
Unity Version 2022.3.20f1
Fxn 0.0.30 (from npm package manager)
Platform: Bluestacks Android Emulator on Windows x64

**Bluestacks Instance Specs:**
Version: Bluestacks 5.21
Platform: Android 11 (ARM64, ARM32, x86_64 & x86_32 support)
Graphics Library: OpenGL
CPU Alloc: 4 Cores
Memory: 2 GB

How to Reproduce:
Step 1: Create Bluestacks Instance based on Specs
Step 2: Build Unity Project to Apk to support only ARM64 (Debug)
Step 3: Install Apk to Bluestacks Instance
Step 4: Run Apk in Bluestacks

Here is logcat file:
[fxn-0030-vk-0022-crash-logcat.zip](https://github.com/user-attachments/files/17709063/fxn-0030-vk-0022-crash.zip)

**Comment by olokobayusuf** [comment] 2024-11-11 23:46
This is likely caused by the unsupported simulator environment.

**Comment by olokobayusuf** [comment] 2024-11-23 15:01
The cause has been found. Working on a fix.

**Comment by olokobayusuf** [comment] 2024-12-10 14:08
Fix coming later today.

**Comment by olokobayusuf** [comment] 2024-12-10 19:25
[Fixed in 0.0.31](https://github.com/fxnai/fxn3d/releases/tag/0.0.31).

**Closed as completed by olokobayusuf** 2024-12-10 19:25 UTC
Labels: android
